#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if package.json has changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -q '^package.json$'; then
  echo "package.json has changed. Running npm install..."
  npm install --silent
else
  echo "No changes in package.json."
fi
